# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170115_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='are',
            new_name='area',
        ),
    ]
